spring:
  profiles:
    active: dev #默认为开发环境
  datasource:
    #mysql数据库
    url: jdbc:mysql://localhost:3306/springflutter
    #数据库用户名
    username: root
    #密码
    password: wei@989322
    mysqllocation: mysql-connector-java-8.0.11.jar
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

server:
  port: 8089 #服务运行端口

mybatis:
  mapper-locations:
  - classpath:mapper/*.xml #mybatis 对应的mapper路径

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 259200 #JWT的超期限时间(60*60*24*3)
  expirationRefreshToken: 54432000 #JWT的超期限时间(60*60*24*90)
  tokenHead: Bearer  #JWT负载中拿到开头
file:
  UPLOADED_FOLDER: /my_computer/project/spring_flutter/image/
  UPLOADED_PATH: /image/
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称

redis:
  host: localhost # Redis服务器地址
  database: 0 # Redis数据库索引（默认为0）
  port: 6379 # Redis服务器连接端口
  password: # Redis服务器连接密码（默认为空）
  jedis:
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
  timeout: 3000ms # 连接超时时间（毫秒）
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 300 # 验证码超期时间

