spring:
  profiles:
    active: dev #默认为开发环境


mybatis:
  mapper-locations:
  - classpath:mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 1814400 #JWT的超期限时间(60*60*24*3)
  expirationRefreshToken: 54432000 #JWT的超期限时间(60*60*24*90)
  tokenHead: Bearer  #JWT负载中拿到开头

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称
